// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Database;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220503151412_Index")]
    partial class Index
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Server.Database.Models.Index.SniffModel", b =>
                {
                    b.Property<string>("MD5")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<uint>("BuildVersion")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("FileSize")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("IndexedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PathInArchive")
                        .HasColumnType("longtext");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Uploader")
                        .HasColumnType("longtext");

                    b.HasKey("MD5");

                    b.ToTable("SniffsIndex");
                });

            modelBuilder.Entity("Server.Database.Models.Index.SniffNumberFieldModel", b =>
                {
                    b.Property<string>("SniffModelId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("Field")
                        .HasColumnType("int");

                    b.Property<long>("Value")
                        .HasColumnType("bigint");

                    b.HasKey("SniffModelId", "Field", "Value");

                    b.ToTable("SniffNumbers");
                });

            modelBuilder.Entity("Server.Database.Models.Index.SniffTextFieldModel", b =>
                {
                    b.Property<string>("SniffModelId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("Field")
                        .HasColumnType("int");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SniffModelId", "Field", "Id");

                    b.ToTable("SniffTexts");
                });

            modelBuilder.Entity("Server.Database.Models.LogModel", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Ip")
                        .HasColumnType("longtext");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Key");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Server.Database.Models.UserModel", b =>
                {
                    b.Property<string>("User")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("User");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Server.Database.Models.Index.SniffNumberFieldModel", b =>
                {
                    b.HasOne("Server.Database.Models.Index.SniffModel", "SniffModel")
                        .WithMany()
                        .HasForeignKey("SniffModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SniffModel");
                });

            modelBuilder.Entity("Server.Database.Models.Index.SniffTextFieldModel", b =>
                {
                    b.HasOne("Server.Database.Models.Index.SniffModel", "SniffModel")
                        .WithMany()
                        .HasForeignKey("SniffModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SniffModel");
                });
#pragma warning restore 612, 618
        }
    }
}
